# Generated by Django 2.0.5 on 2018-05-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180529_1121'),
        ('project', '0003_auto_20180529_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_modules',
            name='employee',
        ),
        migrations.AddField(
            model_name='project_modules',
            name='employee',
            field=models.ManyToManyField(to='employee.Employee', verbose_name='list of employees'),
        ),
    ]
