# Generated by Django 2.0.5 on 2018-05-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180529_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_modules',
            name='assign',
        ),
    ]
