# Generated by Django 2.0.5 on 2018-05-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180529_1121'),
        ('project', '0005_remove_project_modules_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_modules',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='employee.Employee'),
        ),
    ]
