# Generated by Django 2.0.5 on 2018-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=250)),
                ('c_location', models.CharField(max_length=250)),
                ('c_code', models.CharField(max_length=250)),
                ('c_category', models.CharField(choices=[('finance', 'Finance'), ('consulting', 'Consulting'), ('data analytics', 'Data Analytics'), ('construction', 'Contruction'), ('mining', 'Mining'), ('oil and gas', 'Oil and Gas'), ('IT', 'IT'), ('business', 'Business'), ('services', 'Services'), ('others', 'Others')], max_length=250)),
                ('c_projects', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
